package com.qualityinspection.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.*;
import com.qualityinspection.dto.ApiDtos.*;
import com.qualityinspection.model.*;
import com.qualityinspection.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.awt.Color;
import java.io.*;
import java.nio.file.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Report generation service.
 * Uses OpenPDF (iText fork) to generate PDF inspection reports.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ReportService {

    private final ReportRepository     reportRepository;
    private final InspectionRepository inspectionRepository;
    private final UserRepository       userRepository;

    @Value("${app.reports.dir}")
    private String reportsDir;

    private static final DateTimeFormatter DISPLAY_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Generates a PDF report for the given inspection and saves it to disk + DB.
     *
     * @param inspectionId inspection to report on
     * @param username     user requesting the report
     * @return byte[] — PDF file bytes (also written to disk)
     */
    @Transactional
    public byte[] generateReport(Long inspectionId, String username) throws Exception {
        Inspection inspection = inspectionRepository.findById(inspectionId)
                .orElseThrow(() -> new NoSuchElementException("Inspection not found: " + inspectionId));

        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new IllegalArgumentException("User not found: " + username));

        byte[] pdfBytes = buildPdf(inspection);

        // Persist to file
        String reportCode = "RPT-" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));
        Path dir  = Paths.get(reportsDir);
        Files.createDirectories(dir);
        Path file = dir.resolve(reportCode + ".pdf");
        Files.write(file, pdfBytes);

        // Persist to DB
        Report report = Report.builder()
                .reportCode(reportCode)
                .inspection(inspection)
                .generatedBy(user)
                .filePath(file.toString())
                .fileSizeKb((int)(pdfBytes.length / 1024))
                .summary("Inspection " + inspection.getInspectionCode() + " — " + inspection.getStatus().name())
                .build();
        reportRepository.save(report);

        log.info("Report generated: {}", reportCode);
        return pdfBytes;
    }

    /** Lists all reports ordered by date descending. */
    public List<ReportSummaryDto> listReports() {
        return reportRepository.findByOrderByGeneratedAtDesc()
                .stream()
                .map(this::toDto)
                .collect(Collectors.toList());
    }

    // ---- PDF Builder ----

    private byte[] buildPdf(Inspection ins) throws Exception {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4, 50, 50, 70, 50);
        PdfWriter writer = PdfWriter.getInstance(doc, bos);

        doc.open();

        // ---- Header ----
        Font titleFont   = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.WHITE);
        Font headerFont  = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.decode("#1e3a5f"));
        Font normalFont  = FontFactory.getFont(FontFactory.HELVETICA, 11, Color.DARK_GRAY);
        Font smallFont   = FontFactory.getFont(FontFactory.HELVETICA, 9,  Color.GRAY);

        // Blue header bar
        PdfPTable headerTable = new PdfPTable(1);
        headerTable.setWidthPercentage(100);
        PdfPCell headerCell = new PdfPCell(new Phrase("  AI Quality Inspection Report", titleFont));
        headerCell.setBackgroundColor(Color.decode("#1e3a5f"));
        headerCell.setPadding(14);
        headerCell.setBorder(Rectangle.NO_BORDER);
        headerTable.addCell(headerCell);
        doc.add(headerTable);

        doc.add(Chunk.NEWLINE);

        // ---- Report meta ----
        doc.add(new Paragraph("Report Code : " + "RPT-" + ins.getInspectionCode(), headerFont));
        doc.add(new Paragraph("Generated At: " + LocalDateTime.now().format(DISPLAY_FMT), normalFont));
        doc.add(new Paragraph("Generated By: " + ins.getUser().getFullName(), normalFont));
        doc.add(new LineSeparator());
        doc.add(Chunk.NEWLINE);

        // ---- Inspection Info ----
        doc.add(new Paragraph("INSPECTION DETAILS", headerFont));
        doc.add(Chunk.NEWLINE);

        PdfPTable infoTable = new PdfPTable(2);
        infoTable.setWidthPercentage(100);
        infoTable.setWidths(new float[]{1, 2});

        addInfoRow(infoTable, "Inspection Code", ins.getInspectionCode(), normalFont);
        addInfoRow(infoTable, "Product",         ins.getProduct().getProductName() + " (" + ins.getProduct().getProductCode() + ")", normalFont);
        addInfoRow(infoTable, "Inspected At",    ins.getInspectedAt().format(DISPLAY_FMT), normalFont);
        addInfoRow(infoTable, "Inspected By",    ins.getUser().getFullName(), normalFont);
        addInfoRow(infoTable, "Image File",      ins.getImageFilename(), normalFont);

        // Status with colour
        Color statusColor = ins.getStatus() == Inspection.Status.GOOD ? Color.decode("#28a745") : Color.decode("#dc3545");
        Font statusFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, statusColor);
        PdfPCell labelCell  = new PdfPCell(new Phrase("Status", normalFont));
        PdfPCell valueCell  = new PdfPCell(new Phrase(ins.getStatus().name(), statusFont));
        styleInfoCell(labelCell); styleInfoCell(valueCell);
        infoTable.addCell(labelCell); infoTable.addCell(valueCell);

        addInfoRow(infoTable, "Confidence",    ins.getConfidence() + "%", normalFont);
        addInfoRow(infoTable, "Recommendation", ins.getRecommendation() != null ? ins.getRecommendation().name() : "N/A", normalFont);
        addInfoRow(infoTable, "Notes",          ins.getNotes(), normalFont);
        doc.add(infoTable);

        doc.add(Chunk.NEWLINE);

        // ---- Defects ----
        if (ins.getDefects() != null && !ins.getDefects().isEmpty()) {
            doc.add(new Paragraph("DETECTED DEFECTS", headerFont));
            doc.add(Chunk.NEWLINE);

            PdfPTable defectTable = new PdfPTable(5);
            defectTable.setWidthPercentage(100);
            defectTable.setWidths(new float[]{2, 1.5f, 1.5f, 1.5f, 3});

            // Header row
            for (String h : new String[]{"Defect Type","Severity","Confidence","Bounding Box","Description"}) {
                PdfPCell c = new PdfPCell(new Phrase(h, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
                c.setBackgroundColor(Color.decode("#2c5282"));
                c.setPadding(6);
                defectTable.addCell(c);
            }

            for (Defect d : ins.getDefects()) {
                defectTable.addCell(makeCell(d.getDefectType(), normalFont));
                defectTable.addCell(makeCell(d.getSeverity().name(), normalFont));
                defectTable.addCell(makeCell(d.getConfidence() + "%", normalFont));
                String bbox = (d.getBboxX() != null)
                        ? d.getBboxX() + "," + d.getBboxY() + " " + d.getBboxWidth() + "×" + d.getBboxHeight()
                        : "N/A";
                defectTable.addCell(makeCell(bbox, normalFont));
                defectTable.addCell(makeCell(d.getDescription(), normalFont));
            }
            doc.add(defectTable);
        } else {
            doc.add(new Paragraph("No defects detected. Product passed quality inspection.", normalFont));
        }

        doc.add(Chunk.NEWLINE);
        doc.add(new LineSeparator());
        doc.add(new Paragraph("This report was automatically generated by the AI Quality Inspection System.", smallFont));

        doc.close();
        return bos.toByteArray();
    }

    private void addInfoRow(PdfPTable table, String label, String value, Font font) {
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.decode("#1e3a5f"));
        PdfPCell l = new PdfPCell(new Phrase(label, labelFont));
        PdfPCell v = new PdfPCell(new Phrase(value != null ? value : "N/A", font));
        styleInfoCell(l); styleInfoCell(v);
        table.addCell(l); table.addCell(v);
    }

    private void styleInfoCell(PdfPCell cell) {
        cell.setPadding(6);
        cell.setBorderColor(Color.LIGHT_GRAY);
    }

    private PdfPCell makeCell(String text, Font font) {
        PdfPCell c = new PdfPCell(new Phrase(text != null ? text : "N/A", font));
        c.setPadding(5);
        return c;
    }

    private ReportSummaryDto toDto(Report r) {
        return ReportSummaryDto.builder()
                .id(r.getId())
                .reportCode(r.getReportCode())
                .inspectionCode(r.getInspection().getInspectionCode())
                .productName(r.getInspection().getProduct().getProductName())
                .generatedBy(r.getGeneratedBy().getFullName())
                .fileSizeKb(r.getFileSizeKb())
                .summary(r.getSummary())
                .generatedAt(r.getGeneratedAt().toString())
                .build();
    }
}
